version: '3'
services:
  frontend:
    container_name: scribe-frontend
    env_file: .env
    build:
      context: ./scribe-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./scribe-frontend:/usr/app/scribe-frontend
      - /usr/app/scribe-frontend/node_modules
  database:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=backend-db
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  scribe-app-network:
    driver: bridge
